
-- Desafio: Bairros por cidade

DECLARE @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50)
DECLARE @CONTADOR INT, @LINHAS INT
DECLARE @TABELA_BAIRROS TABLE(BAIRROS VARCHAR(50))

SET @CONTADOR = 0
SET @CIDADE = 'Rio de Janeiro'

SELECT @LINHAS = COUNT(*) 
FROM (SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES] WHERE @CIDADE = CIDADE) LINHAS

WHILE @CONTADOR < @LINHAS
BEGIN
    SELECT DISTINCT @BAIRRO = BAIRRO FROM [TABELA DE CLIENTES] WHERE @CIDADE = CIDADE
	ORDER BY BAIRRO
	OFFSET @CONTADOR ROWS
	FETCH NEXT 1 ROWS ONLY;
	INSERT INTO @TABELA_BAIRROS VALUES (@BAIRRO)
    SET @CONTADOR = @CONTADOR + 1
END

SELECT * FROM @TABELA_BAIRROS