
-- Desafio: lista de nomes de funcionários

DECLARE @NOME VARCHAR(100)
DECLARE CURSOR_FUNCIONARIO CURSOR FOR SELECT NOME FROM [TABELA DE VENDEDORES]
OPEN CURSOR_FUNCIONARIO
FETCH NEXT FROM CURSOR_FUNCIONARIO INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Nome do Vendedor: ' + @NOME
	FETCH NEXT FROM CURSOR_FUNCIONARIO INTO @NOME
END

DEALLOCATE CURSOR_FUNCIONARIO

--=======================================================================================================--

-- Desafio 2: vendas por mês

DECLARE @JANEIRO MONEY, @FEVEREIRO MONEY, @MARCO MONEY, @ABRIL MONEY, @MAIO MONEY, @JUNHO MONEY,
        @JULHO MONEY, @AGOSTO MONEY, @SETEMBRO MONEY, @OUTUBRO MONEY, @NOVEMBRO MONEY, @DEZEMBRO MONEY

DECLARE @DATA_VENDA DATE, @VALOR_VENDA MONEY;

DECLARE CURSOR_VENDAS CURSOR FOR SELECT DATA_VENDA, VALOR_VENDA FROM VENDAS
OPEN CURSOR_VENDAS 
FETCH NEXT FROM CURSOR_VENDAS INTO @DATA_VENDA, @VALOR_VENDA
WHILE @@FETCH_STATUS = 0
BEGIN
	IF MONTH(@DATA_VENDA) = 1
        SET @JANEIRO = @JANEIRO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 2
        SET @FEVEREIRO = @FEVEREIRO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 3
        SET @MARCO = @MARCO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 4
        SET @ABRIL = @ABRIL + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 5
        SET @MAIO = @MAIO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 6
        SET @JUNHO = @JUNHO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 7
        SET @JULHO = @JULHO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 8
        SET @AGOSTO = @AGOSTO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 9
        SET @SETEMBRO = @SETEMBRO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 10
        SET @OUTUBRO = @OUTUBRO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 11
        SET @NOVEMBRO = @NOVEMBRO + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 12
        SET @DEZEMBRO = @DEZEMBRO + @VALOR_VENDA

	FETCH NEXT FROM CURSOR_VENDAS INTO @DATA_VENDA, @VALOR_VENDA
END

DEALLOCATE CURSOR_VENDAS

PRINT 'Janeiro: ' + CAST(@JANEIRO AS VARCHAR(20))
PRINT 'Fevereiro: ' + CAST(@FEVEREIRO AS VARCHAR(20))
PRINT 'Março: ' + CAST(@MARCO AS VARCHAR(20))
PRINT 'Abril: ' + CAST(@ABRIL AS VARCHAR(20))
PRINT 'Maio: ' + CAST(@MAIO AS VARCHAR(20))
PRINT 'Junho: ' + CAST(@JUNHO AS VARCHAR(20))
PRINT 'Julho: ' + CAST(@JULHO AS VARCHAR(20))
PRINT 'Agosto: ' + CAST(@AGOSTO AS VARCHAR(20))
PRINT 'Setembro: ' + CAST(@SETEMBRO AS VARCHAR(20))
PRINT 'Outubro: ' + CAST(@OUTUBRO AS VARCHAR(20))
PRINT 'Novembro: ' + CAST(@NOVEMBRO AS VARCHAR(20))
PRINT 'Dezembro: ' + CAST(@DEZEMBRO AS VARCHAR(20))

--=======================================================================================================--

-- Desafio: seleção de vendedor

DECLARE @VENDEDOR_ALEATORIO VARCHAR(12), @VALOR_INICIAL INT, @VALOR_FINAL INT, @ALEATORIO INT, @CONTADOR INT

SET @VALOR_INICIAL = 1
SET @CONTADOR = 1

SELECT @VALOR_FINAL = COUNT(*) FROM [TABELA DE VENDEDORES]
SET @ALEATORIO = dbo.NumeroAleatorio(@VALOR_INICIAL, @VALOR_FINAL)
DECLARE CURSOR_VENDEDOR_ALEATORIO CURSOR FOR SELECT MATRICULA FROM [TABELA DE VENDEDORES]
OPEN CURSOR_VENDEDOR_ALEATORIO
FETCH NEXT FROM CURSOR_VENDEDOR_ALEATORIO INTO @VENDEDOR_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
	FETCH NEXT FROM CURSOR_VENDEDOR_ALEATORIO INTO @VENDEDOR_ALEATORIO
	SET @CONTADOR = @CONTADOR + 1
END

CLOSE CURSOR_VENDEDOR_ALEATORIO
DEALLOCATE CURSOR_VENDEDOR_ALEATORIO

SELECT @VENDEDOR_ALEATORIO AS MATRICULA, @ALEATORIO AS [NÚMERO ALEATÓRIO]

--=======================================================================================================--
