
-- Desafio: relatório de vendas

CREATE PROCEDURE FaturamentoPorDepartamento(@DATA_INICIAL DATE, @DATA_FINAL DATE)
AS
BEGIN
	DECLARE @DEPARTAMENTO TABLE (SABOR VARCHAR(20), TIPO_FRUTA VARCHAR(20))
	INSERT INTO @DEPARTAMENTO 
	SELECT DISTINCT SABOR, 'FRUTAS NÃO CÍTRICAS' AS TIPO_FRUTA 
	FROM [TABELA DE PRODUTOS]  
	WHERE SABOR IN ('Açai','Cereja','Cereja/Maça','Maça','Manga','Maracujá','Melância')
	UNION
	SELECT DISTINCT SABOR, 'FRUTAS CÍTRICAS' AS TIPO_FRUTA 
	FROM [TABELA DE PRODUTOS]
	WHERE SABOR IN ('Laranja','Uva','Limão','Morango','Morango/Limão','Lima/Limão')

	SELECT D.TIPO_FRUTA, SUM(INF.QUANTIDADE * INF.[PREÇO]) AS FATURAMENTO
	FROM [ITENS NOTAS FISCAIS] INF
	INNER JOIN [TABELA DE PRODUTOS] TP
	ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN @DEPARTAMENTO D
	ON D.SABOR = TP.SABOR
	WHERE NF.DATA >= @DATA_INICIAL AND NF.DATA <= @DATA_FINAL
	GROUP BY D.TIPO_FRUTA
END;

FaturamentoPorDepartamento '2016-01-01', '2016-01-15'