
-- Desafio: faturamento por bairro

CREATE FUNCTION FaturamentoBairro(@BAIRRO VARCHAR(50))
RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(INF.QUANTIDADE * INF.[PREÇO])
	FROM [ITENS NOTAS FISCAIS] INF
	INNER JOIN [NOTAS FISCAIS] NF
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN [TABELA DE CLIENTES] TC
	ON TC.CPF = NF.CPF
	WHERE TC.BAIRRO = @BAIRRO
	RETURN @FATURAMENTO
END

SELECT dbo.FaturamentoBairro('Santo Amaro')
