
-- Desafio 1
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

--=============================================================================================================--

-- Desafio 2
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS WHERE
CODIGO_DO_PRODUTO IN (SELECT INF.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS  INF
                      INNER JOIN TABELA_DE_PRODUTOS TP 
                      ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
                      GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
					  HAVING SUM(INF.QUANTIDADE) > 394000);

--=============================================================================================================--

-- Desafio 3
SELECT PV.CODIGO_DO_PRODUTO, PV.NOME_DO_PRODUTO, PV.QUANTIDADE
FROM (SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
      FROM ITENS_NOTAS_FISCAIS INF
      INNER JOIN TABELA_DE_PRODUTOS TP 
      ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
      GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) PV 
WHERE PV.QUANTIDADE > 394000 
ORDER BY PV.QUANTIDADE DESC;

--=============================================================================================================--

-- Desafio 4

-- Criando a Visão
CREATE VIEW QUANTIDADES_TOTAIS AS 
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;

-- Usando a Visão
SELECT * FROM QUANTIDADES_TOTAIS
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;

--=============================================================================================================--

