
-- Desafio 1
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
STR((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100, 10,2) AS PERCENTUAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN (SELECT NF.CPF, 
            CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, 
            SUM(INF.QUANTIDADE) QUANTIDADE_TOTAL
            FROM NOTAS_FISCAIS NF
            INNER JOIN ITENS_NOTAS_FISCAIS INF
            ON NF.NUMERO = INF.NUMERO
            GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)) AS TV
ON TV.CPF = TC.CPF
WHERE (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0

--=============================================================================================================--

-- Desafio 2
SELECT 
VS.TAMANHO, VS.ANO, VS.VENDA_ANO,
STR(CONVERT(FLOAT,VS.VENDA_ANO) / CONVERT(FLOAT,VA.VENDA_TOTAL_ANO) * 100,10,2) + '%' AS PERCENTUAL
FROM 
(
SELECT 
TP.TAMANHO, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2015'
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA) 
) VS
INNER JOIN
(
SELECT 
YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY YEAR(NF.DATA_VENDA) 
) VA
ON VS.ANO = VA.ANO
ORDER BY VS.VENDA_ANO DESC

--=============================================================================================================--