DROP TABLE [TABELA DE VENDEDORES]

CREATE TABLE [TABELA DE VENDEORES] (
[MATRICULA] VARCHAR(5) NOT NULL, 
[NOME] VARCHAR(100),
[CIDADE] VARCHAR(100),
[PERCENTUAL COMISSAO] FLOAT NOT NULL,
[DATA INICIO] DATE NOT NULL,
[TEM DEPENDENTE] BIT 
);

ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA]);

INSERT INTO [TABELA DE VENDEDORES]
VALUES 
('00239','Alberto de Sá Verneck','São Paulo',0.08,'2020-06-05',1);

SELECT * FROM [TABELA DE VENDEDORES]